### ISSUE TITLE
No Issue - Awesome Performance, Thanks!

### ISSUE THREAD

**Issue by m-j-g** [mcaubrey/clay_containers#12]
Just wanted to tell ya, that I had implemented neumorphic elements in my app using https://pub.dev/packages/flutter_neumorphic.

I have a decent number of elements, and was experiencing some mild jank when scrolling.  After months of dealing with it, scaling back, etc.  I just replaced a page's elements with your clay_containers and it became smooth as can be.  

So, Thank you for making yours with low overhead, efficient, and performant!

**Comment by MichaelCharles** [comment]
Thank you!
