### ISSUE TITLE
Question: can this package be a BoxDecoration?

### ISSUE THREAD

**Issue by lukepighetti** [mcaubrey/clay_containers#5]
I'm curious if this package could be distilled into a BoxDecoration class. If so, we may be able to use AnimatedContainer with it and get implicit animations for free.

**Comment by wurikiji** [comment]
I simply change this package to an implicit animation version. You can use https://pub.dev/packages/clay_containers_plus
You can use `ClayContainer` as same as `AnimateContainer`. I also wrap the `ClayText` with `AnimatedDefaultTextStyle` so that you can also implicitly animate the `ClayText`.
