### ISSUE TITLE
[Feature Request] Null-safety support

### ISSUE THREAD

**Issue by al8n** [mcaubrey/clay_containers#8]
Hi, please support the null-safety version.

**Comment by sameeerkashyap** [comment]
If there's no WIP on this, I can help!

**Comment by MichaelCharles** [comment]
@Sameerkash there's no WIP and I'm open to pull requests 👍

**Comment by sameeerkashyap** [comment]
> @Sameerkash there's no WIP and I'm open to pull requests 👍 

Will be up in a few days.

**Comment by MichaelCharles** [comment]
Thanks! It has been published as 0.3.0
